apiVersion: v1 
kind: Service
metadata:
  name: yolo_app
spec:
  selector:
    app: yolo_app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo_app
  template:
    metadata:
      labels:
        app: yolo_app
    spec:
      containers:
        - name: app
          image: yolo
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
